BEGIN; 
 
 DROP TABLE IF EXISTS USERS, QUESTIONS, REPLIES CASCADE;

 CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL
 );

 CREATE TABLE QUESTIONS(
  ID SERIAL PRIMARY KEY,
  CONTENT TEXT NOT NULL, 
  USER_ID INT,
  CONSTRAINT USER_ID FOREIGN KEY(USER_ID)
  REFERENCES USERS(ID)
 );

 CREATE TABLE REPLIES(
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    QUESTION_ID INT,
    CONSTRAINT QUESTION_ID FOREIGN KEY(QUESTION_ID)
    REFERENCES QUESTIONS(ID)
 );

 INSERT INTO USERS(USERNAME, PASSWORD) VALUES
 ('FADEZAK100', '123'),
 ('ADMIN', '1234');

 INSERT INTO QUESTIONS(CONTENT, USER_ID) VALUES 
  ('WHAT IS YOUR NAME?', 1),
  ('WHAT IS YOUR LAST NAME?', 1),
  ('WHOS YOU BESTFRIEND?', 1);

 INSERT INTO REPLIES(CONTENT, QUESTION_ID) VALUES 
 ('FADI', 1),
 ('ZAQOUT', 2),
 ('NONE', 3); 


COMMIT;